rvm: '2.2.3'

language: ruby

bundler_args: --without production

services:
  - postgresql

before_script:
  - psql -c 'create database instragram_clone_test;' -U postgres

script: bundle exec rspec spec
