# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3936294a246145932b19a1a1e33ee85e2f5cbfb21283d62964c8042496196662fa339fbe9ff6dd4281f5fc36f9fc1b89c428652a5e252e74824b3c69f24042

test:
  secret_key_base: 7e1cbfd7cceae33fd921da2c45cbcd1a1abcd4d0b6d4adac202382f90e3664e0c02b138647b7a18d93e457c94efce4cdc173b4f1a31946e397d3bf550bc3f873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
